name: flutter_wordpress
description: This library uses WordPress REST-API-V2 to provide a way for your application to
  interact with your WordPress website.
version: 0.3.0-nullsafety.0

homepage: https://github.com/dreamsoftin/flutter_wordpress

environment:
  sdk: '>=2.16.2 <3.0.0'

dependencies:
  http: ^0.13.4
